[relaychain]
default_command = "polkadot"
default_args = ["-linfo,runtime::contracts=debug"]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9942

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  ws_port = 9943

[[parachains]]
id = 1000
cumulus_based = true

  [[parachains.collators]]
  name = "contracts-collator-1"
  ws_port = 9944
  command = "./target/release/demo-collator"
  args = ["--force-authoring", "-linfo,runtime::contracts=debug,xcm=trace" ]

[[parachains]]
id = 1001
chain = "statemine-local"
cumulus_based = true

  [[parachains.collators]]
  name = "statemine-collator-1"
  ws_port = 9945
  command = "polkadot-parachain"
  args = ["--force-authoring", "-linfo,xcm=trace" ]


[[hrmp_channels]]
sender = 1000
recipient = 1001
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 1001
recipient = 1000
max_capacity = 8
max_message_size = 512

